name: PUBLISH

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/cd-generic-dot-net.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      backend-repo: ${{ github.repository }}
      project-path: Vyracare.Api.Proceedings.csproj
      output-dir: backend-publish
      api-gateway-name: vyracare-api-proceedings
      lambda-function-name: vyracare-api-proceedings
      lambda-handler: Vyracare.Api.Proceedings
      route-base-path: api/proceedings
    secrets: inherit
